### ISSUE TITLE
User and password for the MQTT-Broker

### ISSUE THREAD

**Issue by PLCHome** [tobiasbick/twincat2mqtt#2]
Hello thanks for the great project, it has taken a lot of work.
I have extended the connection procedure by a user with password.
I would be glad if you take this into the main branch.
I know that it will be transmitted unencrypted.

Please merge or deny....

**Comment by tobiasbick** [comment]
I merged it, thanks for your commit.

**Comment by Andrey2509** [comment]
> Hello thanks for the great project, it has taken a lot of work.
> I have extended the connection procedure by a user with password.
> I would be glad if you take this into the main branch.
> I know that it will be transmitted unencrypted.
> 
> Please merge or deny....

Please send me any working example for TC2 (TC3 if TC2 not found)
