### ISSUE TITLE
Unknown identifier HOST_TO_BE16

### ISSUE THREAD

**Issue by Andrey2509** [tobiasbick/twincat2mqtt#3]
Try to build for target beckhoff CX9010, twincat 2.11.2303
![mqtt](https://user-images.githubusercontent.com/12102946/54429542-a305f100-4742-11e9-893e-1d588d380f17.png)

**Comment by PLCHome** [comment]
You need the "TwinCAT TCP/IP Connection Server" / "TcpIp.Lib"

**Comment by Andrey2509** [comment]
> You need the "TwinCAT TCP/IP Connection Server" / "TcpIp.Lib"

I have it.
![mqtt2](https://user-images.githubusercontent.com/12102946/54429991-ef056580-4743-11e9-8913-02ccc8d823cc.png)

**Comment by Andrey2509** [comment]
I added TcUtilities.lib and problem was solved.
